<?php
/**
 * NOVIUS OS - Web OS for digital communication
 *
 * @copyright  2011 Novius
 * @license    GNU Affero General Public License v3 or (at your option) any later version
 *             http://www.gnu.org/licenses/agpl-3.0.html
 * @link http://www.novius-os.org
 */

namespace Nos;

class Orm_Behaviour_Url extends Orm_Behaviour
{
	/**
	 * publication_bool_property
	 * publication_start_property
	 * publication_end_property
	 */
	protected $_properties = array();

    /**
     * Returns all available URL for this item. The array contains:
     *
     *   page_id::item_url_enhancer_part => full_url (relative to base)
     *
     * This way, we get all the informations we want:
     *  - The page ID
     *  - The URL generated by the enhancer
     *  - The current full URL (current page URL + enhancer part)
     *
     * When retrieving only the first URL, we get only the first value (current full URL, without page_id).
     *
     * If there's no result, the function will either return null or empty array()
     *
     * @param  \Nos\Model  $item
     * @param  array       $params
     * @return  null|string|array
     */
    public function urls($item, $params = array()) {
        $urls = array();
        foreach ($this->_properties['enhancers'] as $enhancer_name)
        {
            foreach (\Nos\Tools_Enhancer::url_item($enhancer_name, $item, $params) as $key => $url)
            {
                $urls[$key] = $url;
            }
        }
        return $urls;
    }

    public function url_canonical($object, $params = array()) {
        $params['canonical'] = true;
        return $this->url($object, $params);
    }

    // @todo Figure out the appripriate method name : url() / url_item() / other()?
    public function url($item, $params = array()) {

        $canonical = \Arr::get($params, 'canonical', false);
        unset($params['canonical']);
        if ($canonical) {
            unset($params['urlPath']);
        }

        // Front-office (enhancer context) = calculate urlPath based on current page, except if canonical URL was asked for
        if (!$canonical && ($main_controller = \Nos\Nos::main_controller()) instanceof \Nos\Controller_Front) {
            $params['urlPath'] = $main_controller->getEnhancedUrlPath();
        }

        // Real canonical URL can only be computed using default sharable data
        if ($canonical && $item::behaviours('Nos\Orm_Behaviour_Sharable')) {
            $default_nuggets = $item->get_catcher_nuggets(Model_Content_Nuggets::DEFAULT_CATCHER);
            $nuggets = $default_nuggets->content_data;
            $nugget_url = \Arr::get($nuggets, \Nos\DataCatcher::TYPE_URL, false);
            if (!empty($nugget_url)) {
                list($page_id, $itemPath) = explode('::', $nugget_url);
                \Config::load(APPPATH.'data'.DS.'config'.DS.'url_enhanced.php', 'data::url_enhanced');
                $url_enhanced = \Config::get('url_enhanced', array());
                $url_enhanced = array_flip($url_enhanced);
                $urlPath = \Arr::get($url_enhanced, $page_id, false);
                if ($urlPath !== false) {
                    $params['urlPath'] = $urlPath;
                } else {
                    // This page does not contain an enhancer anymore... Can't use it to generate the canonical URL...
                }
            }
        }

        $urls = $this->urls($item, $params);
        return \Arr::get($urls, 0, null);
    }
}